/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Store_CONSTANTS_H
#define Store_CONSTANTS_H

#include "Store_types.h"



class StoreConstants {
 public:
  StoreConstants();

};

extern const StoreConstants g_Store_constants;



#endif
