// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Store.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class StoreHandler : virtual public StoreIf {
 public:
  StoreHandler() {
    // Your initialization goes here
  }

  int32_t getPrice(const std::string& item) {
    // Your implementation goes here
    printf("getPrice\n");
  }

  bool order(const std::string& item, const int16_t amount) {
    // Your implementation goes here
    printf("order\n");
  }

  void getReceipt(std::vector<Order> & _return) {
    // Your implementation goes here
    printf("getReceipt\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<StoreHandler> handler(new StoreHandler());
  shared_ptr<TProcessor> processor(new StoreProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

